Version 0.1 of Zoo database....
georgedobrev/Blankfactor_Interns_Basics pull request #142
Opened 2023-05-09 11:05 UTC by IvayloPetkovBlankfactor

2023-05-09 11:13 UTC, KalinVasilev-at-blankfactor approved these changes

2023-05-09 12:08 UTC, IvayloPetkovBlankfactor commented
Thanks for the review!

2023-05-12 06:58 UTC, pyankov00 requested changes

2023-05-12 06:58 UTC, pyankov00 commented on OOP Inheritance, Polymorphism and Abstraction_IvayloPetkov/App/Program.cs
> +        }
Why you inherit interface without implementing it ? Refer to this link for more information why to not do this https://www.bytehide.com/blog/interface-segregation-principle-in-csharp-solid-principles#:~:text=The%20Interface%20Segregation%20Principle%2C%20introduced,are%20irrelevant%20to%20their%20needs.

2023-05-12 09:23 UTC, IvayloPetkovBlankfactor commented
I will close this pull request because it also has a .ds_store conflict that I cannot resolve, and open a new request.

2023-05-12 09:23 UTC, closed without merging