Abstraction_And_Inheritance
georgedobrev/Blankfactor_Interns_Basics pull request #148
Opened 2023-05-10 05:50 UTC by aleksandararsov

2023-05-10 08:50 UTC, KalinVasilev-at-blankfactor requested changes
Please, exclude any binary files. Also, try putting interfaces and classes in their own files. 
In real world code no one puts separate classes in the same file. Each class or interface has it's own file, except inner classes but that's the single exception to the rule. 
Please, make the necessary corrections.

2023-05-11 07:01 UTC, KalinVasilev-at-blankfactor requested changes
Good job on the split! But you still have the old files in the repo along with the binaries. Please, remove them. 
Thanks!

2023-05-11 07:01 UTC, aleksandararsov commented
I updated classes and interfaces.

2023-05-11 07:12 UTC, KalinVasilev-at-blankfactor approved these changes

2023-05-11 07:12 UTC, merged