Martin bardarov
georgedobrev/Blankfactor_Interns_Basics pull request #16
Opened 2023-04-28 06:23 UTC by martinbardarov-exe

2023-05-01 12:53 UTC, Turnikman88 requested changes

2023-05-01 12:53 UTC, Turnikman88 commented on Loops_MartinBardarov/IsPalindrome.java
> +    public boolean isPalindrome(String word) {
word needs to be Integer, then converted to String

2023-05-01 12:53 UTC, Turnikman88 commented on Loops_MartinBardarov/IsPalindrome.java
> +        input1.reverse();
Can you solve the problem without using this method?

2023-05-01 12:53 UTC, Turnikman88 commented on README.md
> -# Blankfactor_Interns_Basics
remove the changes

2023-05-02 06:48 UTC, martinbardarov-exe commented
Done

2023-05-05 06:18 UTC, closed without merging