Loops Ivaylo Petkov
georgedobrev/Blankfactor_Interns_Basics pull request #18
Opened 2023-04-28 07:41 UTC by IvayloPetkovBlankfactor

2023-04-28 12:00 UTC, pyankov00 requested changes
Do NOT use top level statements for more code readability. 
https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements => use the old way described here.
All method's names should start with capital letter!

2023-04-28 12:00 UTC, pyankov00 commented on Loops_IvayloPetkov/Merge two strings/Merge_Two_Strings/Program.cs
What will happen if one of the words is with different length than the other ? 
Also save the result in a variable and the print it

2023-04-28 12:00 UTC, pyankov00 commented on Loops_IvayloPetkov/Check the sum/Check_the_sum/Program.cs
What happens when you have for example the letter "f" in the word ? In this way you will have to write 30 and more  ifs for every letter? Think of a way without all of these if else-s

2023-04-28 12:00 UTC, pyankov00 commented on Loops_IvayloPetkov/Check if it is palindrome/Check_if_it_is_palindrome/Program.cs
In this way with number 1231 the solution is wrong.

2023-04-28 12:13 UTC, pyankov00 commented on Loops_IvayloPetkov/Check the sum/Check_the_sum/Program.cs
Taka a look to ASCII table for the correct solution

2023-05-01 20:32 UTC, IvayloPetkovBlankfactor commented
Sorry for not uploading the "BuzzFizz" task... I was experiencing some problems with GitHub on the mac and it looks like that it wasn't uploaded. I have did the same on my PC and uploaded everything that needed to be fixed. I fixed the problems with the top level statements and used StringBuilder in two of the tasks, as for the ASCII table, I read the solution on the internet, I haven't come with this idea on my own. I just don't get it how the code works.

2023-05-10 08:20 UTC, IvayloPetkovBlankfactor commented
Fixed the .DS_Store problem

2023-05-12 06:36 UTC, pyankov00 commented
Resolve conflicts

2023-05-12 08:52 UTC, closed without merging